version: '3'
services:
  api:
    image: gemanueldev/utils-api-go:latest
    container_name: utils-api-go
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
